<?php

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_woo-product-extras',
    'title' => 'Propel Catalog Extras',
    'fields' => array (
      /*******/
      array (
        'key' => 'field_course_sales_page_image',
        'label' => 'Course Sales Page Image',
        'name' => 'course_sales_page_image',
        'type' => 'image',
        'instructions' => 'This is the image that shows on the individual course sale page. ',
        'save_format' => 'url',
        'preview_size' => 'full',
        'library' => 'all',
      ),
      array (
        'key' => 'field_video_embed',
        'label' => 'Course Sales Page Video',
        'name' => 'video_embed',
        'type' => 'oembed',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'width' => 345,
        'height' => 230,
      ),
      array (
        'key' => 'field_you_will_learn',
        'label' => 'You Will Learn',
        'name' => 'you_will_learn',
        'type' => 'wysiwyg',
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      /*******/
      array (
        'key' => 'field_product_course_price_for_members',
        'label' => 'Price for Members',
        'name' => 'price_for_members',
        'type' => 'text',
        'instructions' => 'Use this field to display the price for members',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_catalog_description',
        'label' => 'Catalog Description',
        'name' => 'catalog_description',
        'type' => 'textarea',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_product_course_more_info',
        'label' => 'Course More Info Button Label',
        'name' => 'course_more_info',
        'type' => 'text',
        'instructions' => 'Edit the Course Info button text',
        'default_value' => 'Course Info',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_product_course_authors',
        'label' => 'Course Authors',
        'name' => 'course_authors',
        'type' => 'text',
        'instructions' => 'Use this field for how the author names will display on the my courses page and the course catalog',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_product_credit_type',
        'label' => 'Credit Type',
        'name' => 'credit_type',
        'type' => 'text',
        'instructions' => 'Use this field for how the certificate info will display on the my courses page above the claim button',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_product_expires_in_days',
        'label' => 'Expires In (days)',
        'name' => 'course_expires_in_days',
        'type' => 'text',
        'instructions' => 'How many days does a user have access to this course?',
        'default_value' => '365',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '5',
      ),
      array (
        'key' => 'field_catalog_product_flag',
        'label' => 'Show Catalog Product Flag',
        'name' => 'show_catalog_product_flag',
        'type' => 'true_false',
        'instructions' => 'Set this field to True to show a flag on the catalog page',
        'message' => '',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_catalog_product_flag_label',
        'label' => 'Catalog Product Flag Label',
        'name' => 'catalog_product_flag_label',
        'type' => 'text',
        'instructions' => 'The label for the flag on the Catalog page',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_catalog_product_flag',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => 'update',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => 35,
      ),
      array (
        'key' => 'field_catalog_product_flag_content',
        'label' => 'Catalog Product Flag Popover Content',
        'name' => 'catalog_product_flag_popover_content',
        'type' => 'wysiwyg',
        'instructions' => 'The content for the popover when the flag is clicked',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_catalog_product_flag',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'toolbar' => 'basic',
        'media_upload' => 'no',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'product',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}
